version: "3.8"
services:
  otel_collector:
    image: otel/opentelemetry-collector-contrib
    ports:
      - 4318:4318
      - 4319:4319
      - 4320:4320
    command: ["--config=/etc/config.yaml", "${OTELCOL_ARGS}"]
    volumes:
      - ./config.yaml:/etc/config.yaml
